vich_uploader:
    db_driver: orm

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
        company_logos:
            uri_prefix: /uploads/companies/logos
            upload_destination: '%kernel.project_dir%/public/uploads/companies/logos'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
