easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    #resource: '..\..\src\Controller\Admin\EasyAdmin\AdminController.php'
    prefix: /admin
    type: annotation
