# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    delivery_addresses: ['astoros@hotmail.fr']
    stream_options:
      ssl:
        allow_self_signed: true
        verify_peer: false
