#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout
page_inscription:
    path: /insrciption-entreprise
    controller: App\Controller\MainController::inscriptionEntreprise
