## YAML Template.
---
easy_admin:
    design:
        menu:        
            -
                label: Utilisateurs
                icon: users
                entity: User
            -
                label: Entreprises
                icon: building
                entity: Company