## YAML Template.
---
easy_admin:
    design:
        menu:        
            -
                label: Utilisateurs
                icon: users
                children:
                    -
                        label: Tous les utilisateurs
                        entity: User
                    -
                        label: Administrateurs
                        entity: Admin
                    -
                        label: Clients
                        entity: Client
            -
                label: Entreprises
                icon: building
                entity: Company
            -
                label: Branches
                icon: folder-o
                entity: Branch