## YAML Template.
---
easy_admin:
    entities:
        User:
            class: App\Entity\Admin\User
            list:
                title: Liste des utilisateurs
                actions: [ '-edit', '-new' ]